### ISSUE TITLE
Bank Tab Data Blank

### ISSUE THREAD

**Issue by wellkunnected** [richardxyx/Play-Money#5]
Hey guys,

I was able to get this app running on my iphone 6+ running the latest version of OS with no issues! Despite what the author wrote about the code being a mess I actually got errors or warnings while building the app so KUDOS to Richard for a job well done! The only thing that I found is that the Bank tab is empty, or atleast the view is. I was thinking this tab would be used for adding your Banks info to be able to send money to other players so I suppose a good question to ask here is this, is this app suppose to function as a "pay other people" app or just a UI template for a "pay other people" app? Thanks for the help!

**Comment by richardneitzke** [comment]
Hey, as I said before, this is a project that I did when I started with iOS development and it is not supposed to be working extremely well.

Anyways, the "Bank" tab should be filled with the players after you add them in the "Add Player" tab. Make sure to pick a name, start amount of cash and a token for every player you add. After that, they should come up in the "Bank" tab. You can transfer money by tapping on the players in the "Bank" tab or in the "Transfer Money" tab.

The app should still work. It is made for managing money in games like Monopoly.

I hope I could help you a little, make sure to comment here if you need any help :)

**Comment by wellkunnected** [comment]
Awesome! So it's more like a utility used when playing a game like monopoly? Pretty cool, I'll toy around with it a bit more and get back to you with my findings! Keep being awesome bro :)

**Comment by richardneitzke** [comment]
Yes, it basically replaces cash in Monopoly.
Thanks, you too!

**Comment by wellkunnected** [comment]
Sweet! Thanks again dude.
